---

name: Test Multiarch Action
on: [push, pull_request]
jobs:
  do_thing:
    name: do a thing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/run-on-arch-action
        name: do a thing on aarch64 fedora
        id: athing
        with:
          arch: aarch64
          distro: manylinux2014
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --env MYENV='hi mom'
          run: |
            uname -a
            echo $MYENV
            echo ::set-output name=uname::$(uname -a)
            echo ::set-output name=pythonls::$(ls /opt/python)

      - name: get output
        run: |
          echo "uname output was ${{ steps.athing.outputs.uname }}"
          echo "ls output was ${{ steps.athing.outputs.pythonls }}"
